export const data = [
  {
    id: 1,
    gymName: "WTF : Military Gym",
    rating: "⭐⭐⭐⭐⭐",
    address: "Chaman Awan office, Sector 15",
    distance: "3.66 minutes away | 2.44 km",
    price: 3000,
  },
  {
    id: 2,
    gymName: "WTF : Hybrid Gym",
    rating: "⭐⭐⭐⭐⭐",
    address: "A 452 Basement, New Ashok Nagar",
    distance: "3.18 minutes away | 2.12 km",
    price: 3500,
  },
  {
    id: 3,
    gymName: "WTF : The Iron Pumpers Gym",
    rating: "⭐⭐⭐⭐⭐",
    address: "Patparganj Road, Pocket 5",
    distance: "5.22 minutes away | 3.48 km",
    price: 3800,
  },
  {
    id: 4,
    gymName: "WTF : The Fitness Point Gym",
    rating: "⭐⭐⭐⭐⭐",
    address: "Sector 53, Noida",
    distance: "5.71 minutes away | 3.81 km",
    price: 3500,
  },
  {
    id: 5,
    gymName: "WTF : Human Fit X",
    rating: "⭐⭐⭐⭐⭐",
    address: "C-254, Sector 44",
    distance: "7.26 minutes away | 4.84 km",
    price: 4000,
  },
  {
    id: 6,
    gymName: "WTF : The Inferno ( Pandav Nagar )",
    rating: "⭐⭐⭐⭐",
    address: "99 D Park Road, 99",
    distance: "7.51 minutes away | 5.01 km",
    price: 3000,
  },
  {
    id: 7,
    gymName: "WTF : Wild Fitness Club",
    rating: "⭐⭐⭐⭐⭐",
    address: "Sector 49, C Block",
    distance: "7.92 minutes away | 5.28 km",
    price: 3500,
  },
  {
    id: 8,
    gymName: "WTF : Swear to fit fitness club",
    rating: "⭐⭐⭐⭐⭐",
    address: "BS - 102, Basai, Sector 70, Basai",
    distance: "7.92 minutes away | 5.28 km",
    price: 3000,
  },
  {
    id: 9,
    gymName: "WTF : Dalyfstyle Gym",
    rating: "⭐⭐⭐⭐⭐",
    address: "Indirapuram, Aditya Mega City",
    distance: "8.28 minutes away | 5.52 km",
    price: 3500,
  },
  {
    id: 10,
    gymName: "WTF : The Inferno ( Shakarpur )",
    rating: "⭐⭐⭐⭐⭐",
    address: "Main Market, Main Market",
    distance: "8.71 minutes away | 5.81 km",
    price: 4000,
  },
  {
    id: 11,
    gymName: "WTF : The Inferno ( Laxmi Nagar )",
    rating: "⭐⭐⭐⭐⭐",
    address: "Laxmi Nagar, Laxmi Nagar",
    distance: "10.27 minutes away | 6.85 km",
    price: 3500,
  },
];
